config/routes.rb
Rails.application.routes.draw do

  # device顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
  }

  # ゲストログイン用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customer/sessions#guest_sign_in'
  end

  # device施設用
  # URL /facility/sign_in ...
  devise_for :facility, skip: [:registrations, :passwords], controllers: {
  sessions: 'facility/sessions'
  }

  # device管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 顧客用
  scope module: :customer do
    root to: "homes#top"
    get '/about' => 'homes#about'
    get 'customers/mypage' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/confirm_withdrawal' => 'customers#confirm_withdrawal', as: 'customers_confirm_withdrawal'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'customers_withdrawal'
    resources :children, only: [:new, :create, :edit, :update]
    patch 'children/:id/disable_child' => 'children#disable_child', as: 'disable_child'
    resources :families, only: [:new, :create, :edit, :update]
    patch 'families/:id/disable_family' => 'families#disable_family', as: 'disable_family'
    post 'reservations/confirm' => 'reservations#confirm'
    get 'reservations/thanks' => 'reservations#thanks'
    get 'reservations/confirm_allergy' => 'reservations#confirm_allergy_view'
    patch 'reservations/confirm_allergy' => 'reservations#confirm_allergy'
    patch 'reservations/:id/cancel' => 'reservations#cancel', as: 'reservations_cancel'
    resources :reservations, only: [:new, :create, :index, :show, :edit, :update]
    resources :relationships, only: [:create, :index, :destroy]
    resources :facilities, only: [:index, :show]
    get '/search' => 'searches#search'
    resources :menus, only: [:index]
  end

  # 施設用
  namespace :facility do
    get '/' => 'homes#top', as: 'top'
    get 'reservations/situation' => 'reservations#situation'
    resources :reservations, only: [:index, :show, :edit, :update]
    patch 'reservations/:id/cancel' => 'reservations#cancel', as: 'reservations_cancel'
    resources :reservation_conditions, only: [:new, :create, :index, :edit, :update, :destroy]
    resources :facilities, only: [:show, :edit, :update]
    resources :customers, only: [:show, :update]
    get '/search' => 'searches#search'
    resources :menus, only: [:new, :create, :index, :edit, :update, :destroy]
  end

  # 管理者用
  namespace :admin do
    resources :reservations, only: [:index, :show]
    resources :customers, only: [:index, :show, :edit]
    get 'facilities/:id/situation' => 'facilities#situation', as: 'facility_situation'
    resources :facilities, only: [:new, :create, :index, :show, :edit, :update]
    patch 'facilities/:id/withdrawal' => 'facilities#withdrawal', as: 'facility_withdrawal'
    get '/search' => 'searches#search'
  end

end

app/controllers/admin/facilities_controller.rb
class Admin::FacilitiesController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_facility, only: [:show, :edit, :update, :situation]

  def new
    @facility = Facility.new
  end

  def create
    @facility = Facility.new(facility_params)
    if @facility.save
      flash[:notice] = "施設登録が完了しました。"
      redirect_to admin_facility_path(@facility)
    else
      flash.now[:notice] = "施設登録ができませんでした。"
      render :new
    end
  end

  def index
    @facilities = Facility.page(params[:page])
  end

  def show
  end

  def edit
  end

  def update
    if @facility.update(facility_params)
      flash[:notice] = "修正が完了しました。"
      redirect_to admin_facility_path(@facility)
    else
      flash.now[:notice] = "修正の保存に失敗しました。"
      render :edit
    end
  end

  def withdrawal
    facility = Facility.find(params[:id])
    facility.update(is_active: false)
    flash[:notice] = "閉園処理を行いました。"
    redirect_to admin_facilities_path
  end

  def situation
    @reservations = @facility.reservations.validation_checked.order(day: :desc)
  end

  private
  def facility_params
    params.require(:facility).permit(:name, :name_kana, :email, :password, :postal_code, :address, :telephone_number, :website, :business_day, :business_hours, :inquiry_hours, :closed_day, :childcare_hours, :target_age, :school_meal, :fee, :message)
  end

  def ensure_facility
    @facility = Facility.find(params[:id])
  end

end

app/controllers/customer/facilities_controller.rb
class Customer::FacilitiesController < ApplicationController
  before_action :authenticate_customer!

  def index
    @facilities = Facility.page(params[:page])
  end

  def show
    @facility = Facility.find(params[:id])
    @reservations = @facility.reservations.validation_checked.order(day: :desc)
  end

  private
  def facility_params
    params.require(:facility).permit(:name, :name_kana, :email, :password, :postal_code, :address, :telephone_number, :website, :business_day, :business_hours, :inquiry_hours, :closed_day, :childcare_hours, :target_age, :school_meal, :fee, :message)
  end
end

app/controllers/customer/menus_controller.rb
class Customer::MenusController < ApplicationController
  before_action :authenticate_customer!

  def index
    @facility = Facility.find(params[:facility_id])
    @menus = @facility.menus.page(params[:page]).per(25)
  end

end

app/controllers/facility/confirmations_controller.rb
# frozen_string_literal: true

class Facility::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/facility/customers_controller.rb
class Facility::CustomersController < ApplicationController
  before_action :authenticate_facility!
  before_action :ensure_customer, only: [:show, :edit, :update, :withdrawal]

  def show
    @active_children = @customer.children.where(is_active: true)
    @active_families = @customer.families.where(is_active: true)
  end

  def update
    if @customer.update(customer_params)
      flash[:notice] = "メモの保存が完了しました。"
      redirect_to facility_customer_path(@customer.id)
    else
      @active_children = @customer.children.where(is_active: true)
      @active_families = @customer.families.where(is_active: true)
      flash.now[:notice] = "メモの保存ができませんでした。"
      render :show
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:administrator_notes)
  end

  def ensure_customer
    @customer = Customer.find(params[:id])
  end

end

app/controllers/facility/facilities_controller.rb
class Facility::FacilitiesController < ApplicationController
  before_action :authenticate_facility!
  before_action :ensure_facility, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @facility.update(facility_params)
      flash[:notice] = "修正が完了しました。"
      redirect_to facility_facility_path(@facility)
    else
      flash.now[:notice] = "修正の保存に失敗しました。"
      render :edit
    end
  end

  private
  def facility_params
    params.require(:facility).permit(:name, :name_kana, :email, :password, :postal_code, :address, :telephone_number, :website, :business_day, :business_hours, :inquiry_hours, :closed_day, :childcare_hours, :target_age, :school_meal, :fee, :message, :is_active)
  end

  def ensure_facility
    @facility = Facility.find(params[:id])
  end

end

app/controllers/facility/homes_controller.rb
class Facility::HomesController < ApplicationController
  before_action :authenticate_facility!

  def top
    @reservations = current_facility.reservations.where(day: Date.today)
  end
end

app/controllers/facility/menus_controller.rb
class Facility::MenusController < ApplicationController
  before_action :authenticate_facility!
  before_action :ensure_menu, only: [:show, :edit, :update]

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.facilities << Facility.find(params[:menu][:facility_id])
    if @menu.save
      flash[:notice] = "献立の登録が完了しました。"
      redirect_to facility_menus_path
    else
      flash.now[:notice] = "献立の登録ができませんでした。"
      render new_facility_menu_path
    end
  end

  def index
    @menus = current_facility.menus.order(:date).page(params[:page]).per(25)
  end

  def edit
  end

  def update
    if @menu.update(menu_params)
      flash[:notice] = "献立の修正が完了しました。"
      redirect_to facility_menus_path
    else
      flash.now[:notice] = "献立の修正ができませんでした。"
      render 'edit'
    end
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    flash[:notice] = "献立の削除が完了しました。"
    redirect_to facility_menus_path
  end

  private

  def menu_params
    params.require(:menu).permit(:date, :school_lunch, :snack, :ingredient)
  end

  def ensure_menu
    @menu = Menu.find(params[:id])
  end

end

app/controllers/facility/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Facility::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/facility/passwords_controller.rb
# frozen_string_literal: true

class Facility::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/facility/registrations_controller.rb
# frozen_string_literal: true

class Facility::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/facility/reservation_conditions_controller.rb
class Facility::ReservationConditionsController < ApplicationController
  before_action :authenticate_facility!

  def new
    @reservation_conditions = ReservationConditions.new
    @facility = current_facility
  end

  def create
    @reservation_conditions.facility_id = current_facility.id
    if @reservation.save
      flash[:notice] = "予約条件の登録が完了しました。"
      redirect_to facility_reservation_conditions_path
    else
      flash.now[:notice] = "予約条件の登録ができませんでした。"
      render new
    end
  end

private
  def reservation_conditions_params
    params.require(:reservation_conditions).permit(:unavailable_days, :unavailable_times, :maximum_number_of_people, :facility_id)
  end

end

app/controllers/facility/reservations_controller.rb
class Facility::ReservationsController < ApplicationController
  before_action :authenticate_facility!
  before_action :ensure_reservation, only: [:show, :edit, :update, :cancel]

  def index
    @reservations = current_facility.reservations.order(day: "DESC").page(params[:page])
  end

  def show
    @main_pick_up_person = Family.find(@reservation.main_pick_up_person)
    @emergency_contact_1 = Family.find(@reservation.emergency_contact_1)
    if @reservation.emergency_contact_2.present?
      @emergency_contact_2 = Family.find(@reservation.emergency_contact_2)
    end
  end

  def edit
    @children = Child.where(customer_id: @reservation.customer_id, is_active: true)
    @families = Family.where(customer_id: @reservation.customer_id, is_active: true)
    @main_pick_up_person = Family.find(@reservation.main_pick_up_person)
    @emergency_contact_1 = Family.find(@reservation.emergency_contact_1)
    if @reservation.emergency_contact_2.present?
      @emergency_contact_2 = Family.find(@reservation.emergency_contact_2)
    end
  end

  def update
    if @reservation.update(reservation_params)
      if params[:reservation][:wants_meal_service] == "false"
        @reservation.update(is_allergy_checked: false)
      elsif params[:reservation][:wants_meal_service] == "true"
        @reservation.update(is_allergy_checked: true)
      end
      flash[:notice] = "修正が完了しました。"
      redirect_to facility_reservation_path(@reservation)
    else
      @children = Child.where(customer_id: @reservation.customer_id, is_active: true)
      @families = Family.where(customer_id: @reservation.customer_id, is_active: true)
      @main_pick_up_person = Family.find(@reservation.main_pick_up_person)
      @emergency_contact_1 = Family.find(@reservation.emergency_contact_1)
      if @reservation.emergency_contact_2.present?
        @emergency_contact_2 = Family.find(@reservation.emergency_contact_2)
      end
      flash.now[:notice] = "修正の保存に失敗しました。"
      render :edit
    end
  end

  def cancel
    @reservation.update(is_valid_reservation: false)
    if @reservation.wants_meal_service
      @reservation.update(is_allergy_checked: false)
    end
    flash[:notice] = "キャンセルが完了しました。"
    redirect_to facility_reservations_path
  end

  def situation
    @facility = current_facility
    @reservations = @facility.reservations.validation_checked.order(day: :desc)
  end

  private
  def reservation_params
    params.require(:reservation).permit(:day, :start_time, :end_time, :wants_meal_service, :purpose_of_use, :main_pick_up_person, :emergency_contact_1, :emergency_contact_2, :customer_id, :facility_id, :child_id, :family_id, :menu_id)
  end

  def ensure_reservation
    @reservation = current_facility.reservations.find(params[:id])
  end

end

app/controllers/facility/searches_controller.rb
class Facility::SearchesController < ApplicationController
  before_action :authenticate_facility!

  def search
    @word = params[:word]
    @model = params[:model]
    @search = params[:search]
    @facility = Facility.find(params[:facility])

    if @model == "Menu"
      @records = Menu.search_for(@word, @search, @facility)
    else
      @records = Reservation.search_for(@word, @search, @facility)
    end
  end

end

app/controllers/facility/unlocks_controller.rb
# frozen_string_literal: true

class Facility::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/facilities_helper.rb
module Admin::FacilitiesHelper
end

app/helpers/customer/facilities_helper.rb
module Customer::FacilitiesHelper
end

app/views/facility/menus/_index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-xl-12 col-lg-12 mx-auto">
      <div class="table-responsive">
        <% if menus.blank? %>
          <p class="mb-5">検索結果が見つかりませんでした。</p>
          <br><br><br><br><br><br><br><br>
        <% else %>
        <table class="table border border-black table-light">
          <thead>
            <tr class="table-secondary text-center">
              <th class="align-middle", style="width: 19%;">日付</th>
              <th class="align-middle", style="width: 22%;">給食</th>
              <th class="align-middle", style="width: 20%;">おやつ</th>
              <th class="align-middle", style="width: 29%;">食材</th>
              <th class="align-middle", style="width: 10%;"></th>
            </tr>
          </thead>
          <tbody>
            <% menus.each do |menu| %>
            <tr>
              <td class="align-middle", style="width: 19%;"><%= menu.date.strftime('%Y年%m月%d日 ') %><%= japanese_day(menu.date) %></td>
              <td class="align-middle", style="width: 22%;"><%= menu.school_lunch %></td>
              <td class="align-middle", style="width: 20%;"><%= menu.snack %></td>
              <td class="align-middle", style="width: 29%;"><%= menu.ingredient %></td>
              <td class="align-middle text-center", style="width: 10%;">
                <%= link_to "編集", edit_facility_menu_path(menu.id), class: "btn btn-custom px-3" %><br>
                <%= link_to "削除", facility_menu_path(menu.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger px-3 mt-2" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/facility/menus/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
    <h2 class="font-weight-bold mb-5">献立編集</h2>
    </div>
  </div>

    <div class="row">
    <% if @menu.errors.any? %>
    <div class="col-xl-10 col-lg-10 mx-auto alert alert-info" role="alert">
      <%= @menu.errors.count %>件のエラーが発生しました
      <ul>
        <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>

  <%= form_with model: @menu, url: facility_menu_path(@menu.id), method: :patch do |f| %>
  <div class="row">
    <div class="col-xl-8 col-lg-8 mx-auto">
      <div class="form-group">
        <%= f.label :"日付", class: "font-weight-bold" %><br>
        <%= f.date_select :date, {start_year: Date.current.year, end_year: Date.current.year + 10, prompt: { year: '年', month: '月', day: '日' }}, value: f.object.date %>
      </div><br>
      <div class="form-group">
        <%= f.label :"給食", class: "font-weight-bold" %><br>
        <%= f.text_area :school_lunch, class: "form-control", id: "exampleFormControlTextarea1", rows: "4", value: f.object.school_lunch %>
      </div><br>
      <div class="form-group">
        <%= f.label :"おやつ", class: "font-weight-bold" %><br>
        <%= f.text_field :snack, class: "form-control", value: f.object.snack %>
      </div><br>
      <div class="form-group">
        <%= f.label :"食材", class: "font-weight-bold" %><br>
        <%= f.text_area :ingredient, class: "form-control", id: "exampleFormControlTextarea1", rows: "4", value: f.object.ingredient %>
      </div><br>
    </div>
  </div>

  <div class="row mt-3 mb-5">
    <div class="mx-auto">
      <%= link_to "戻る", :back, class: "btn btn-outline-secondary px-4 mr-5" %><%= f.submit "献立を修正", class: "font-weight-bold btn btn-custom px-4" %>
    </div>
  </div>
  <% end %><br><br>
</div>

app/views/facility/menus/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
    <h2 class="font-weight-bold mb-5"><%= current_facility.name %>献立一覧</h2>
    </div>
  </div>

  <%= render 'facility/searches/menu_search' %>

  <div class="row mt-5">
    <div class="col-xl-12 col-lg-12 text-right">
    <%= link_to "献立登録", new_facility_menu_path, class: "btn btn-custom px-4 font-weight-bold mr-3" %>
    </div>
  </div>

  <%= render 'index', menus: @menus, current_facility: @facility %>

  <div class="row mt-5">
    <div class="mx-auto">
      <%= paginate @menus %>
    </div>
  </div>

  <div class="row mt-5 mb-5">
    <div class="mx-auto">
      <%= link_to "戻る", :back, class: "btn btn-outline-secondary px-4" %>
    </div>
  </div>
</div>

app/views/facility/menus/new.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
    <h2 class="font-weight-bold mb-5">献立新規登録</h2>
    </div>
  </div>

  <div class="row">
    <% if @menu.errors.any? %>
    <div class="col-xl-10 col-lg-10 mx-auto alert alert-info" role="alert">
      <%= @menu.errors.count %>件のエラーが発生しました
      <ul>
        <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>

  <%= form_with model: @menu, url: facility_menus_path, method: :post do |f| %>
  <div class="row">
    <div class="col-xl-8 col-lg-8 mx-auto">
      <div class="form-group">
        <%= f.label :"日付", class: "font-weight-bold" %><br>
        <%= f.date_select :date, {start_year: Date.current.year, end_year: Date.current.year + 10, prompt: { year: '年', month: '月', day: '日' }}, value: f.object.date %>
      </div><br>
      <div class="form-group">
        <%= f.label :"給食", class: "font-weight-bold" %><br>
        <%= f.text_area :school_lunch, placeholder: "ごはん、しいたけのすまし汁、豚肉と厚揚げの味噌炒め、小松菜のおひたし、オレンジ", class: "form-control", id: "exampleFormControlTextarea1", rows: "4", value: f.object.school_lunch %>
      </div><br>
      <div class="form-group">
        <%= f.label :"おやつ", class: "font-weight-bold" %><br>
        <%= f.text_field :snack, placeholder: "麦茶、かわめごはん", class: "form-control", value: f.object.snack %>
      </div><br>
      <div class="form-group">
        <%= f.label :"食材", class: "font-weight-bold" %><br>
        <%= f.text_area :ingredient, placeholder: "米、椎茸、玉ねぎ、にんじん、油、三温糖、麩、豚肉、厚揚げ、味噌、小松菜、キャベツ、かつお節、オレンジ、わかめ、米", class: "form-control", id: "exampleFormControlTextarea1", rows: "4", value: f.object.ingredient %>
      </div><br>
    </div>
  </div>

  <div class="row mt-3 mb-5">
    <div class="mx-auto">
      <%= f.hidden_field :facility_id, :value => current_facility.id %>
      <%= link_to "戻る", :back, class: "btn btn-outline-secondary px-4 mr-5" %><%= f.submit "献立を登録", class: "font-weight-bold btn btn-custom px-4" %>
    </div>
  </div>
  <% end %><br><br>
</div>