config/routes.rb
Rails.application.routes.draw do

  # device顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
  }

  # ゲストログイン用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customer/sessions#guest_sign_in'
  end

  # device施設用
  # URL /facility/sign_in ...
  devise_for :facility, skip: [:registrations, :passwords], controllers: {
  sessions: 'facility/sessions'
  }

  # device管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 顧客用
  scope module: :customer do
    root to: "homes#top"
    get '/about' => 'homes#about'
    get 'customers/mypage' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/confirm_withdrawal' => 'customers#confirm_withdrawal', as: 'customers_confirm_withdrawal'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'customers_withdrawal'
    resources :children, only: [:new, :create, :edit, :update]
    patch 'children/:id/disable_child' => 'children#disable_child', as: 'disable_child'
    resources :families, only: [:new, :create, :edit, :update]
    patch 'families/:id/disable_family' => 'families#disable_family', as: 'disable_family'
    post 'reservations/confirm' => 'reservations#confirm'
    get 'reservations/thanks' => 'reservations#thanks'
    get 'reservations/confirm_allergy' => 'reservations#confirm_allergy_view'
    patch 'reservations/confirm_allergy' => 'reservations#confirm_allergy'
    patch 'reservations/:id/cancel' => 'reservations#cancel', as: 'reservations_cancel'
    resources :reservations, only: [:new, :create, :index, :show, :edit, :update]
    resources :relationships, only: [:create, :index, :destroy]
    resources :facilities, only: [:index, :show]
    get '/search' => 'searches#search'
    resources :menus, only: [:index]
  end

  # 施設用
  namespace :facility do
    get '/' => 'homes#top', as: 'top'
    get 'reservations/situation' => 'reservations#situation'
    resources :reservations, only: [:index, :show, :edit, :update]
    patch 'reservations/:id/cancel' => 'reservations#cancel', as: 'reservations_cancel'
    resources :reservation_conditions, only: [:new, :create, :index, :edit, :update, :destroy]
    resources :facilities, only: [:show, :edit, :update]
    resources :customers, only: [:show, :update]
    get '/search' => 'searches#search'
    resources :menus, only: [:new, :create, :index, :edit, :update, :destroy]
  end

  # 管理者用
  namespace :admin do
    resources :reservations, only: [:index, :show]
    resources :customers, only: [:index, :show, :edit]
    get 'facilities/:id/situation' => 'facilities#situation', as: 'facility_situation'
    resources :facilities, only: [:new, :create, :index, :show, :edit, :update]
    patch 'facilities/:id/withdrawal' => 'facilities#withdrawal', as: 'facility_withdrawal'
    get '/search' => 'searches#search'
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_customer, only: [:show, :edit, :update]

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @active_children = @customer.children.where(is_active: true)
    @active_families = @customer.families.where(is_active: true)
  end

  def edit
  end

  private
  def ensure_customer
    @customer = Customer.find(params[:id])
  end

end

app/controllers/customer/children_controller.rb
class Customer::ChildrenController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_child, only: [:show, :edit, :update, :destroy]

  def new
    @customer = Customer.find(current_customer.id)
    @child = Child.new(customer_id: current_customer.id)
  end

  def create
    @customer = Customer.find(current_customer.id)
    @child = Child.new(child_params.merge(customer_id: current_customer.id))
    if @child.save
      flash[:notice] = "お子さまの登録が完了しました。"
      if current_customer.children.count > 1
        redirect_to customers_mypage_path(current_customer)
      else
        redirect_to new_family_path
      end
    else
      flash.now[:notice] = "お子さまの登録ができませんでした。"
      render :new
    end
  end

  def edit
  end

  def update
    if @child.update(child_params)
      flash[:notice] = "修正が完了しました。"
      redirect_to customers_mypage_path(current_customer)
    else
      flash.now[:notice] = "修正に失敗しました。"
      render :edit
    end
  end

  def disable_child
    child = Child.find(params[:id])
    child.update(is_active: false)
    flash[:notice] = "指定されたお子さま情報を無効にしました。"
    redirect_to customers_mypage_path(current_customer)
  end

  private
  def child_params
    params.require(:child).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :birthday, :male, :normal_body_temperature,
    :fever, :has_febrile_seizure, :febrile_seizure_details, :has_dislocation, :dislocation_details, :has_allergy, :allergy_details, :breastfeeding_status,
    :breastfeeding_amount, :situation_after_breastfeeding, :milk_situation_after_baby_food, :amount_of_milk_after_baby_food, :baby_food_progress, :appetite,
    :favorite_food, :hated_food, :how_to_eat, :meal_time, :how_to_lay_it_down, :falling_asleep, :waking_up, :sleeping_position, :is_deep_sleep, :habits_when_sleeping,
    :diaper_usage, :is_sensitive_to_rash, :urination, :defecation, :number_of_defecation, :favorite_game, :favorite_toy, :hospital_name, :hospital_telephone_number,
    :memo, :is_active)
  end

  def ensure_child
    @child = Child.find(params[:id])
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_customer, only: [:show, :edit, :update, :withdrawal]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @active_children = @customer.children.where(is_active: true)
    @active_families = @customer.families.where(is_active: true)
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      flash[:notice] = "修正が完了しました。"
      redirect_to customers_mypage_path(current_customer)
    else
      flash.now[:notice] = "修正に失敗しました。"
      render :edit
    end
  end

  def confirm_withdrawal
  end

  def withdrawal
    reservations = @customer.reservations.where(is_valid_reservation: true)
    reservations.each do |reservation|
      reservation.update(is_valid_reservation: false)
    end
    @customer.update(is_active: false)
    reset_session
    flash[:notice] = "退会処理を実行しました。"
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
  end

  def ensure_customer
    @customer = Customer.find(current_customer.id)
  end

  def ensure_guest_user
    @customer = Customer.find(current_customer.id)
    if @customer.last_name == "guest_" && @customer.first_name == "user"
      redirect_to customers_mypage_path(current_customer) , notice: 'guest_userはアカウント情報編集画面へ遷移できません。'
    end
  end

end

app/controllers/customer/facilities_controller.rb
class Customer::FacilitiesController < ApplicationController
  before_action :authenticate_customer!

  def index
    @facilities = Facility.page(params[:page])
  end

  def show
    @facility = Facility.find(params[:id])
    @reservations = @facility.reservations.validation_checked.order(day: :desc)
  end

  private
  def facility_params
    params.require(:facility).permit(:name, :name_kana, :email, :password, :postal_code, :address, :telephone_number, :website, :business_day, :business_hours, :inquiry_hours, :closed_day, :childcare_hours, :target_age, :school_meal, :fee, :message)
  end
end

app/controllers/customer/families_controller.rb
class Customer::FamiliesController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_family, only: [:show, :edit, :update]

  def new
    @customer = Customer.find(current_customer.id)
    @family = Family.new(customer_id: current_customer.id)
  end

  def create
    @customer = Customer.find(current_customer.id)
    @family = Family.new(family_params.merge(customer_id: current_customer.id))
    if @family.save
      if current_customer.show_image
        current_customer.update(show_image: false)
      end
      flash[:notice] = "家族の登録が完了しました。"
        redirect_to customers_mypage_path(current_customer)
    else
      flash.now[:notice] = "家族の登録ができませんでした。"
      render :new
    end
  end

  def edit
  end

  def update
    if @family.update(family_params)
      flash[:notice] = "修正が完了しました。"
      redirect_to customers_mypage_path(current_customer)
    else
      flash.now[:notice] = "修正に失敗しました。"
      render :edit
    end
  end

  def disable_family
    family = Family.find(params[:id])
    family.update(is_active: false)
    flash[:notice] = "指定された家族情報を無効にしました。"
    redirect_to customers_mypage_path(current_customer)
  end

private

  def family_params
    params.require(:family).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :male, :relationship, :birthday,:telephone_number, :workplace, :workplace_telephone_number, :is_active)
  end

  def ensure_family
    @family = Family.find(params[:id])
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/customer/menus_controller.rb
class Customer::MenusController < ApplicationController
  before_action :authenticate_customer!

  def index
    @facility = Facility.find(params[:facility_id])
    @menus = @facility.menus.page(params[:page]).per(25)
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_up_path_for(resource)
    new_child_path
  end

end

app/controllers/customer/relationships_controller.rb
class Customer::RelationshipsController < ApplicationController
  before_action :authenticate_customer!

  def create
  end

  def index
  end

  def destroy
  end

end

app/controllers/customer/searches_controller.rb
class Customer::SearchesController < ApplicationController
  before_action :authenticate_customer!

  def search
    @word = params[:word]
    @model = params[:model]
    @search = params[:search]

    if @model == "Menu"
      @facility = Facility.find(params[:facility])
      @records = Menu.search_for(@word, @search, @facility)
    else
      @records = Facility.search_for(@word, @search)
    end
  end

end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :customer_state, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    customers_mypage_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  #ゲストログイン用メアクション
  def guest_sign_in
    customer = Customer.guest
    sign_in customer
    redirect_to customers_mypage_path(customer), notice: 'guest_userでログインしました。'
  end

private
  # 会員がアクティブであるかを判断するメソッド
  def customer_state
    # 【処理内容1】 入力されたemailからアカウントを1件取得
    customer = Customer.find_by(email: params[:customer][:email])
    # 【処理内容2】 アカウントを取得できなかった場合、このメソッドを終了する
    return if customer.nil?
    # 【処理内容3】 取得したアカウントのパスワードと入力されたパスワードが一致していない場合、このメソッドを終了する
    return unless customer.valid_password?(params[:customer][:password])
    # 【処理内容4】 アクティブな会員に対する処理
    if customer.is_active
      flash[:notice] = "ログインしました。"
      sign_in(customer)
      redirect_to after_sign_in_path_for(customer)
    # 【処理内容5】 アクティブでない会員に対する処理
    else
      flash[:notice] = "退会済みです。再度登録をしてご利用ください。"
      redirect_to new_customer_registration_path
    end
  end

end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/facility/customers_controller.rb
class Facility::CustomersController < ApplicationController
  before_action :authenticate_facility!
  before_action :ensure_customer, only: [:show, :edit, :update, :withdrawal]

  def show
    @active_children = @customer.children.where(is_active: true)
    @active_families = @customer.families.where(is_active: true)
  end

  def update
    if @customer.update(customer_params)
      flash[:notice] = "メモの保存が完了しました。"
      redirect_to facility_customer_path(@customer.id)
    else
      @active_children = @customer.children.where(is_active: true)
      @active_families = @customer.families.where(is_active: true)
      flash.now[:notice] = "メモの保存ができませんでした。"
      render :show
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:administrator_notes)
  end

  def ensure_customer
    @customer = Customer.find(params[:id])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/customer/families/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
    <h2 class="font-weight-bold mb-5">お子さまの家族編集</h2>
    </div>
  </div>

  <div class="row">
    <% if @family.errors.any? %>
    <div class="col-10 mx-auto alert alert-info" role="alert">
      <%= @family.errors.count %>件のエラーが発生しました
      <ul>
        <% @family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>

  <%= form_with model: @family, url: family_path(@family), method: :patch do |f| %>
  <div class="row">
    <div class="col-xl-8 col-lg-8 mx-auto">
      <p class="red">*印の項目は必須項目です。</p>
      </p>
      <p class="font-weight-bold">【お子さまの家族】</p>
      <div class="field">
        <%= f.label :"家族氏名", class: "font-weight-bold" %><span class="red">*</span><br>
        <%= f.label :"(姓)", class: "font-weight-bold" %>
        <%= f.text_field :last_name, autofocus: true, autocomplete: "name", class: "form-control" %><br>
        <%= f.label :"(名)", class: "font-weight-bold" %>
        <%= f.text_field :first_name, autocomplete: "name", class: "form-control" %><br>
      </div><br>
      <div class="field">
        <%= f.label :"フリガナ", class: "font-weight-bold" %><span class="red">*</span><br>
        <%= f.label :"(セイ)", class: "font-weight-bold" %>
        <%= f.text_field :last_name_kana, autocomplete: "name", class: "form-control" %><br>
        <%= f.label :"(メイ)", class: "font-weight-bold" %>
        <%= f.text_field :first_name_kana, autocomplete: "name", class: "form-control" %><br>
      </div><br>
      <div class="field">
        <%= f.label :"性別", class: "font-weight-bold" %><span class="red">*</span><br>
        <%= f.radio_button :male, "true" %>
        <%= f.label :male_true, "男", class: "mr-5" %>
        <%= f.radio_button :male, "false" %>
        <%= f.label :male_false, "女" %>
      </div><br>
      <div class="field">
        <%= f.label :"続柄", class: "font-weight-bold" %><br>
        <%= f.select :relationship, options_for_select(Family.relationships.keys.map { |key| [I18n.t("enums.family.relationship.#{key}"), key] }, selected: @family.relationship), include_blank: true, class: "form-control" %><br>
      </div><br>
      <div class="field">
        <%= f.label :"生年月日", class: "font-weight-bold" %><span class="red">*</span><br>
        <%= f.date_select :birthday, start_year: 1920, end_year: Date.today.year, prompt: { year: '年', month: '月', day: '日' }, class: "form-control" %><br><br>
      </div><br>
      <div class="field">
        <%= f.label :"電話番号(ハイフンなし)", class: "font-weight-bold" %><span class="red">*</span>
        <%= f.text_field :telephone_number, autocomplete: "tel", class: "form-control" %>
      </div><br><br>
      <div class="field">
        <%= f.label :"勤務先", class: "font-weight-bold" %>
        <%= f.text_field :workplace, class: "form-control" %>
      </div><br><br>
      <div class="field">
        <%= f.label :"勤務先電話番号(ハイフンなし)", class: "font-weight-bold" %>
        <%= f.text_field :workplace_telephone_number, autocomplete: "tel", class: "form-control" %>
      </div><br><br>
    </div>
  </div>

  <div class="row mb-5">
    <div class="mx-auto">
      <%= link_to "戻る", :back, class: "btn btn-outline-secondary px-4 mr-5" %>
      <%= f.submit "修正", class: "font-weight-bold btn btn-custom px-4 mr-5" %>
      <%= link_to "無効にする", disable_family_path(@family), method: :patch, "data-confirm" => "本当に無効にしますか？", class: "font-weight-bold btn btn-danger px-4" %>
    </div>
  </div>
  <% end %><br><br>
</div>

app/views/customer/families/new.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto">
    <h2 class="font-weight-bold mb-5">お子さまの家族登録</h2>
    </div>
  </div>

  <div class="row">
    <% if @family.errors.any? %>
    <div class="col-xl-10 col-lg-10 mx-auto alert alert-info" role="alert">
      <%= @family.errors.count %>件のエラーが発生しました
      <ul>
        <% @family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>

  <% if @customer.show_image && (@customer.last_name != "guest_" || @customer.first_name != "user") %>
  <div class="row mb-5">
    <div class="col-12 text-center">
      <%= image_tag asset_path("family_information_registration.png"), width: "80%" %>
    </div>
  </div>
  <% end %>

  <%= form_with model: @family, url: families_path, method: :post do |f| %>
  <div class="row">
    <div class="col-xl-8 col-lg-8 mx-auto">
      <p class="red">*印の項目は必須項目です。</p>
      <p>予約時の主な送迎者や緊急連絡先を選択する際に必要な情報となります。<br>
        まずは、アカウント登録者の情報から登録してみましょう。<br>
        家族情報の追加はマイページから行えます。<br>
      </p>
      <p class="font-weight-bold mt-5">【お子さまの家族】</p>
      <div class="form-group">
        <%= f.label :"家族氏名", class: "font-weight-bold" %><span class="red">*</span><br>
        <%= f.label :"(姓)", class: "font-weight-bold" %>
        <%= f.text_field :last_name, autofocus: true, autocomplete: "name", placeholder: "令和", class: "form-control" %><br>
        <%= f.label :"(名)", class: "font-weight-bold" %>
        <%= f.text_field :first_name, autocomplete: "name", placeholder: "道子", class: "form-control" %><br>
      </div><br>
      <div class="form-group">
        <%= f.label :"フリガナ", class: "font-weight-bold" %><span class="red">*</span><br>
        <%= f.label :"(セイ)", class: "font-weight-bold" %>
        <%= f.text_field :last_name_kana, autocomplete: "name", placeholder: "レイワ", class: "form-control" %><br>
        <%= f.label :"(メイ)", class: "font-weight-bold" %>
        <%= f.text_field :first_name_kana, autocomplete: "name", placeholder: "ミチコ", class: "form-control" %><br>
      </div><br>
      <div class="form-group">
        <%= f.label :"性別", class: "font-weight-bold" %><span class="red">*</span><br>
        <%= f.radio_button :male, "true" %>
        <%= f.label :male_true, "男", class: "mr-5" %>
        <%= f.radio_button :male, "false" %>
        <%= f.label :male_false, "女" %>
      </div><br>
      <div class="form-group">
        <%= f.label :"続柄", class: "font-weight-bold" %><br>
        <%= f.select :relationship, options_for_select(Family.relationships.keys.map { |key| [I18n.t("enums.family.relationship.#{key}"), key] }, selected: @family.relationship), include_blank: true, class: "form-control" %><br>
      </div><br>
      <div class="form-group">
        <%= f.label :"生年月日", class: "font-weight-bold" %><span class="red">*</span><br>
        <%= f.date_select :birthday, start_year: 1920, end_year: Date.today.year, prompt: { year: '年', month: '月', day: '日' }, class: "form-control" %><br><br>
      </div><br>
      <div class="form-group">
        <%= f.label :"電話番号(ハイフンなし)", class: "font-weight-bold" %><span class="red">*</span>
        <%= f.text_field :telephone_number, autocomplete: "tel", placeholder: "0000000000", class: "form-control" %>
      </div><br><br>
      <div class="form-group">
        <%= f.label :"勤務先", class: "font-weight-bold" %>
        <%= f.text_field :workplace, placeholder: "（株）サンプル", class: "form-control" %>
      </div><br><br>
      <div class="form-group">
        <%= f.label :"勤務先電話番号(ハイフンなし)", class: "font-weight-bold" %>
        <%= f.text_field :workplace_telephone_number, autocomplete: "tel", placeholder: "0000000000", class: "form-control" %>
      </div><br><br>
    </div>
  </div>

  <div class="row mb-5">
    <div class="mx-auto">
      <%= f.submit "家族を登録", class: "font-weight-bold btn btn-custom px-4" %>
    </div>
  </div>
  <% end %><br><br>
</div>